# Use the official PostgreSQL image
FROM postgres:17.5-alpine

# Environment variables for PostgreSQL
ENV POSTGRES_DB=timer
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password

# Expose the PostgreSQL port
EXPOSE 5432
