# Use the official PostgreSQL image
FROM postgres:latest

# Environment variables for PostgreSQL
ENV POSTGRES_DB=timer
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password

# Expose the PostgreSQL port
EXPOSE 5432
